cthulhu/urls.py
from django.conf.urls import patterns, url, include
from django.views.generic import TemplateView, RedirectView
from cthulhu.forms.chargenForms import TiradasForm, OcupacionForm, ArmasForm, HabProfForm, HabIntForm, PersonalesForm
from cthulhu.views import estandar, escenarios
from cthulhu.views.chargen import PersonajeWizard
from cthulhu.api import v1_api
from django.contrib import admin

FORMS = [
    ("tiradas", TiradasForm),
    ("ocupacion", OcupacionForm),
    ("armas", ArmasForm),
    ("habprof", HabProfForm),
    ("habint", HabIntForm),
    ("personales", PersonalesForm)
]

urlpatterns = patterns(
    '',
    url(r'^api', include(v1_api.urls)),
    url(r'^ayudas/nombres$', 'cthulhu.views.estandar.nombres'),
    url(r'^ayudas/calles$', 'cthulhu.views.estandar.calles'),
    url(r'^ayudas$', TemplateView.as_view(template_name='ayudas/ayudas.html')),
    #url(r'^chargen/importar$', 'cthulhu.views.chargen.importar'),
    url(r'^chargen', PersonajeWizard.as_view(FORMS)),
    url(r'^escenarios/escenario/(?P<id>[\d]+)$', 'cthulhu.views.escenarios.escenario'),
    url(r'^escenarios/importar$', 'cthulhu.views.escenarios.importar'),
    #url(r'^escenarios/$', 'cthulhu.views.escenarios.escenarios'),
    url(r'^escenarios', escenarios.escenarios),
    url(r'^$', estandar.index, name='index'),
    #url(r'^$', 'cthulhu.views.estandar.index'),
)

django_cthulhu/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('cthulhu.urls')),
    )

cthulhu/models/partida.py
# -*- coding: utf-8 -*-
from django.db import models


class Escena(models.Model):
    nombre = models.CharField(max_length=200)
    contenido = models.TextField(blank=True)
    escenario = models.ForeignKey('Escenario')
    localizaciones = models.ManyToManyField('Localizacion', blank=True, null=True, related_name='Acontecimiento+')
    pnjs = models.ManyToManyField('PNJ', blank=True, null=True, related_name='Actores+')

    def __unicode__(self):
        return self.nombre

    class Meta:
        ordering = ('nombre',)
        app_label = 'cthulhu'


class Escenario(models.Model):
    nombre = models.CharField(max_length=200, blank=True)
    lugares = models.ManyToManyField('Lugar', blank=True, null=True)

    def __unicode__(self):
        return self.nombre

    class Meta:
        ordering = ('nombre',)
        app_label = 'cthulhu'


class Actores(models.Model):
    escena = models.ForeignKey(Escena)
    pnj = models.ForeignKey('PNJ')
    descripcion = models.TextField(blank=True)

    def __unicode__(self):
        return self.nombre

    class Meta:
        app_label = 'cthulhu'


class Acontecimiento(models.Model):
    escena = models.ForeignKey(Escena)
    localizacion = models.ForeignKey('Localizacion')
    descripcion = models.TextField(blank=True)

    def __unicode__(self):
        return self.nombre

    class Meta:
        app_label = 'cthulhu'

cthulhu/views/escenarios.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render

from cthulhu.models.partida import Escenario


def escenario(request, id):
    escenario = Escenario.objects.get(pk=id)
    return render(request, 'escenarios/escenario.html', {'escenario': escenario})


def importar(request):
    return render(request, 'escenarios/importar.html')


def escenarios(request):
    escenarios = Escenario.objects.all()
    return render(request, 'escenarios/escenarios.html', {'escenarios': escenarios})

templates/escenarios/escenario.html
{% extends 'base.html' %}
{% block title %} Prueba{% endblock %}
{% block cabecera %}{% include "tabs.html" with active_tab='tab2' %}{% endblock %}
{% block barraizq %}{% include "escenarios/escenariolat.html" %}{% endblock %}
{% block contenido %}
    <h1>{{ escenario.nombre }}</h1>
    <h2>{{ escenario.escena_set.all.0 }}</h2>
<p>{{ escenario.escena_set.all.0.contenido }}<p>
{% endblock %}

templates/escenarios/escenariolat.html
<ul class="barraizq">
    <li><a href="#">Editar</a></li>
    <li><a href="#">Exportar a Wiki</a></li>
</ul>
<ul class="barraizq">
    {% for escena in escenario.escena_set.all %}
    <li><a href="#">{{ escena.nombre }}</a></li>
    {% endfor %}
    </ul>

templates/escenarios/escenarios.html
{% extends 'base.html' %}
{% block title %} Prueba{% endblock %}
{% block cabecera %}{% include "tabs.html" with active_tab='tab2' %}{% endblock %}
{% block barraizq %}{% include "escenarios/escenarioslat.html" %}{% endblock %}
{% block contenido %}
<p>Selecciona un escenario:</p>
    {% for escenario in escenarios %}
    <li><a href="escenarios/escenario/{{ escenario.id }}">{{ escenario.nombre}}</a>{{ escenario.lugares.all.0.nombre }}</li>
    {% endfor %}

{% endblock %}

templates/escenarios/escenarioslat.html
<link rel='stylesheet'  href='{{STATIC_URL}}css/barraizq.css'/>
<ul class="barraizq">
    <li><a href="escenarios/importar">Importar Wiki</a></li>
</ul>

templates/escenarios/importar.html
{% extends 'base.html' %}
{% block title %} Prueba{% endblock %}
{% block cabecera %}{% include "tabs.html" with active_tab='tab2' %}{% endblock %}
{% block contenido %}
<p>Selecciona una wiki:</p>

<form method="post" enctype="multipart/form-data">
{% csrf_token %}
    Ruta de la wiki:<input type="text" name="ruta" />
    <input type="submit" name="submit" value="Enviar" />
</form>
{% endblock %}